# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traniee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='traniee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='traniee',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='traniee',
            name='city',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='traniee',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='traniee',
            name='state',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='traniee',
            name='zip_code',
            field=models.CharField(default='', max_length=400),
        ),
    ]
