# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0002_auto_20171027_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=400)),
                ('city', models.CharField(default='', max_length=400)),
                ('state', models.CharField(default='', max_length=400)),
                ('zip_code', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Traniee',
        ),
    ]
